### ISSUE TITLE
spring.redis.database: 1 error

### ISSUE THREAD

**Issue by axinger** [redis/redis-om-spring#156]
```
spring:
  application:
    name: redis-om-demo

  redis:
    host: 192.168.101.143
    port: 6376
#    database: 1
```
this is right

but user database: 1  has error

```
spring:
  application:
    name: redis-om-demo

  redis:
    host: 192.168.101.143
    port: 6376
    database: 1
```

https://github.com/bsbodden/issue-145.git

```
2023-01-18 15:21:52.825 ERROR 25420 --- [io-11013-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is redis.clients.jedis.exceptions.JedisDataException: com.example.CompanyIdx: no such index] with root cause

redis.clients.jedis.exceptions.JedisDataException: com.example.CompanyIdx: no such index
```
