### ISSUE TITLE
Sentinel Support

### ISSUE THREAD

**Issue by lucasleon2107** [redis/redis-om-spring#303]
Hi @bsbodden, I noticed that in the latest version of Redis OM, the Jedis version was upgraded, but the Sentinel connection is still not working. To reproduce the issue, you can use this Docker compose file:

```yaml
version: '3'

services:
  redis-master:
    image: redis/redis-stack-server
    container_name: redis-master
    ports:
      - 6379:6379
  redis-sentinel:
    image: redis/redis-stack-server
    container_name: redis-sentinel
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26379:26379
    depends_on:
      - redis-master
    volumes:
      - ./:/usr/local/etc/redis
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_SENTINEL_PARALLEL_SYNCS=1
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
```

Along with this `sentinel.conf` file:

```
bind 0.0.0.0
port 26379
dir "/tmp"
sentinel monitor mymaster 127.0.0.1 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
```

Then you should deploy a service with Redis OM in the same network as the compose. You will get a log like this one:

```
com.redis.om.spring.RediSearchIndexer    : Skipping index creation for {INDEX} because Failed to connect to any host resolved for DNS name.
```
